name:                hstate
version:             0.1.0.0
github:              "iand675/hstate"
license:             BSD3
author:              "Ian Duncan"
maintainer:          "ian@iankduncan.com"
copyright:           "2021 Ian Duncan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/hstate#readme>

default-extensions:
- DataKinds
- DefaultSignatures
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- GADTs
- InstanceSigs
- KindSignatures
- NoCUSKs
- NoNamedWildCards
- NoStarIsType
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- StandaloneKindSignatures
- TemplateHaskell
- TypeApplications
- TypeFamilies
- TypeOperators
- UndecidableInstances

dependencies:
- base >= 4.7 && < 5
- containers
- primitive
- singletons
- singletons-base
- singletons-th
- vector
- typerep-map

library:
  source-dirs: src

tests:
  hstate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hstate
